# Site settings
title: Ajinkya's CV
description: Ajinkya's CV
favicon: /assets/img/avatar.jpg
baseurl: /
url: https://ajinkyabapat.me/
rss_url: /pages/atom.xml
google_analytics: UA-109858103-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ajinkya Bapat
  title: DevOps Engineer
  address: Pune, India
  email: ajinkyabapat12@gmail.com
  link: http://ddbullfrog.com
  weibo:
  github: AjinkyaBapat
  linkedin: ajinkyabapat
  twitter: ajinkyab12
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow: 6202024
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Ignite Solutions Pvt. Ltd.
      location: Pune, India
      title: DevOps Engineer
      started: 2017
      duration: (2017 - Present)
      description: "I currently work here as a DevOps Engineer. My work involves around following: Cloud(AWS|AZURE), Configuration Management(Ansible), CI/CD, Containerization(Docker|K8S|Rancher), SCM, etc."
    - work2:
      company: DXC Technology
      location: Bangalore, India
      title: DevOps Engineer
      started: 2017
      duration: (Apr 2017 - Aug 2017)
      description: "DXC Technology was formed from the merger of HPE & CSC. I got migrated into it as a result of this merger. I handled similar responsibilities as I was handling in HPE, prior to the merger."
    - work3:
      company: Hewlett Packard Enterprise
      location: Bangalore, India
      title: DevOps Engineer
      started: 2015
      duration: (Nov 2015 - Mar 2017)
      description: "My first company! I worked on several projects after completing my initial training program. I was part of the 'Cloud Automation' team. My work involved around following: Cloud Service Automation(HP CSA), Operation Orhestration(HP OO), Server Automation(HP SA), SCM, Monitoring, Backup Solutions, etc."
  educationHistory:
    - education1:
      organization: University Of Pune
      location: Kopargaon, India
      degree: Bachelor
      major: Computer Engineering
      started: 2012
      duration: (2012 - 2015)
      description: "Graduated with 'First Class with Distinction' grades. Won several prizes in Programming/Coding Competitions. Did my final year project on 'Data Mining'."
    - education2:
      organization: Maharashtra State Board of Technical Education
      location: Kopargaon, India
      degree: Diploma
      major: Information Technology
      started: 2009
      duration: (2009 - 2012)
      description: "Completed my Diploma with Distinction. Got to learn some pretty cool stuff in those 3 years! Learnt to code, learnt to debug, learnt to make 'Software'!"

  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Professional
    - language3:
      name: Marathi
      proficiency: Native
    - language4:
      name: Spanish
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: DevOps Methodologies
      percentage: 70%
    - skill2:
      name: Config. Mgmt.
      percentage: 80%
    - skill3:
      name: CI/CD
      percentage: 70%
    - skill4:
      name: Cloud (AWS|Azure|GCP)
      percentage: 60%
    - skill5:
      name: Containerization
      percentage: 80%
    - skill6:
      name: PYTHON|JAVA|HTML|CSS|Javascript
      percentage: 60%
